pipeline:
  publish:
    image: plugins/docker
    repo: harbor.iinumbers.net/library/tornado-hello
    tags:
    - "latest"
    - "${DRONE_COMMIT_SHA:0:8}"
    registry: harbor.iinumbers.net
    secrets:
    - docker_username
    - docker_password
    when:
      branch:
      - master
      event:
        exclude: pull_request
  deploy:
    image: quay.io/ipedrazas/drone-helm
    skip_tls_verify: true
    chart: ./charts/drone-hello
    release: aaa
    namespace: test
    prefix: prod
    values: secret.regsecret=${PROD_REGSECRET}
    secrets:
    - prod_regsecret
    - prod_api_server
    - prod_kubernetes_token
    when:
      event: deployment
      environment: production
