pipeline:
  test:
    image: abc225666/env
    tags:
    - zzz
    - xxx
    secrets:
    - test
  publish:
    image: plugins/docker
    repo: harbor.iinumbers.net/library/tornado-hello
    tags:
    - "latest"
    - "${DRONE_COMMIT_SHA:0:8}"
    registry: harbor.iinumbers.net
    secrets:
    - docker_username
    - docker_password
    when:
      branch:
      - master
      event:
        exclude: pull_request
