pipeline:
  test:
    image: alpine
    commands:
    - "echo 123>zz"
  test2:
    image: alpine
    commands:
    - "cat zz"
  publish:
    image: plugins/docker
    repo: harbor.iinumbers.net/library/tornado-hello
    tags:
    - "latest"
    - "${DRONE_COMMIT_SHA:0:8}"
    registry: harbor.iinumbers.net
    secrets:
    - docker_username
    - docker_password
    when:
      branch:
      - master
      event:
        exclude: pull_request
