branches:
  master
pipeline:
  publish:
    image: plugins/docker
    repo: harbor.iinumbers.net/library/tornado-hello
    registry: harbor.iinumbers.net
    secrets:
    - docker_username
    - docker_password
