apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-hello
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: drone-hello
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-hello
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-hello
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: drone-hello
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullSecrets:
      - name: regsecret
      ports:
      - name: http
        containerPort: 8888
        protocol: TCP 
